# A basic redirect rule
[[redirects]]
  from = "/a/better-products-resources/"
  to = "/guide/intro"

[[redirects]]
  from = "/a/designing-one-to-one-payment-experiences/"
  to = "/designing-payment-experiences"

[[redirects]]
  from = "/a/mid-year-review-2018/" 
  to = "/"

[[redirects]]
  from = "/a/finding-alignment/"
  to = "/"

[[redirects]]
  from = "/a/what-i-learned-in-2017/"
  to = "/"

[[redirects]]
  from = "/tags/product-management/"
  to = "/"

[[redirects]]
  from = "/tags/web-app-challenge/"
  to = "/"

[[redirects]]
  from = "/tags/life/"
  to = "/"

[[redirects]]
  from = "/tags/resources/"
  to = "/guide/intro"

[[redirects]]
  from = "/tags/case-studies/"
  to = "/articles"

[[redirects]]
  from = "/custom-product-design/"
  to = "/"

[[redirects]]
  from = "/now"
  to = "/about"

[[redirects]]
  from = "/product-leadership-for-teams/"
  to = "/"

[[redirects]]
  from = "/prototyping-software-products/"
  to = "/"

[[redirects]]
  from = "/terms/"
  to = "/"

[[redirects]]
  from = "/user-experience-review/"
  to = "/"

[[redirects]]
  from = "/work-with-me/"
  to = "/"

[[redirects]]
  from = "/onboarding-guide/"
  to = "/guide/intro"

[[redirects]]
  from = "/guide/"
  to = "/guide/intro"

[[redirects]]
  from = "/a/effective-landing-pages/"
  to =  "/guide/intro"

[[redirects]]
  from = "/a/solving-the-right-problems/"
  to =  "/articles"

[[redirects]]
  from = "/a/validating-product-ideas-no-code-required/"
  to = "/articles"

[[redirects]]
  from = "/a/concierge-onboarding/"
  to = "/concierge-onboarding"

[[redirects]]
  from = "/a/designing-payment-experiences/"
  to = "/designing-payment-experiences"

[[redirects]]
  from = "/a/product-market-fit/"
  to = "/product-market-fit"

[[redirects]]
  from = "/a/ship-today/"
  to = "/ship-today"

[[redirects]]
  from = "/a/outcomes/"
  to = "/outcomes"

[[redirects]]
  from = "/a/shipping-value/"
  to = "/shipping-value"

[[redirects]]
  from = "/a/watch-vs-show/"
  to = "/watch-vs-show"

[[redirects]]
  from = "/a/watch-vs-show/"
  to = "/watch-vs-show"

[[redirects]]
  from = "/a/understanding-customer-problems/"
  to = "/understanding-customer-problems"
  
[[redirects]]
  from = "/a/web-app-challenge/"
  to = "/web-app-challenge"

[[redirects]]
  from = "/a"
  to = "/articles"